// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9EIryPjDqw_367UYyLor3z2eFxjsAOYA',
    appId: '1:868698601721:android:69c75f44bdc433a2854a28',
    messagingSenderId: '868698601721',
    projectId: 'bankapp-9798a',
    storageBucket: 'bankapp-9798a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80Zdxm2zI06IT4B3ESuTzgNdgedhPgOo',
    appId: '1:868698601721:ios:d42a4f107c42e680854a28',
    messagingSenderId: '868698601721',
    projectId: 'bankapp-9798a',
    storageBucket: 'bankapp-9798a.appspot.com',
    androidClientId: '868698601721-4ul1obg5ith3ng1roms99u3njbdbp4ju.apps.googleusercontent.com',
    iosClientId: '868698601721-68sbo2f5qnbpggru3dbj3jnh45gcoa6s.apps.googleusercontent.com',
    iosBundleId: 'com.theholylabs.foodiex',
  );

}